brew 'bat'
brew 'exa'
brew 'fish'
brew 'git'
brew 'go'
brew 'helm'
brew 'helmfile'
brew 'highlight'
brew 'httpstat'
brew 'icdiff'
brew 'ifstat'
brew 'imagemagick'
brew 'jq'
brew 'lua'
brew 'massren'
brew 'minikube'
brew 'node'
brew 'openssl'
brew 'pass'
brew 'pngcrush'
brew 'python'
brew 'ruby'
brew 'screenfetch'
brew 'sqlite'
brew 'streamlink'
brew 'ssh-copy-id'
brew 'tree'
brew 'unar'
brew 'youtube-dl'
brew 'zopfli'

cask 'xquartz'

cask 'adobe-acrobat-reader'
cask 'alfred'
cask 'android-file-transfer'
cask 'appcleaner'
cask 'bettertouchtool'
cask 'brave-browser'
cask 'calibre'
cask 'cyberduck'
cask 'disk-inventory-x'
cask 'docker'
cask 'dolphin'
cask 'dropbox'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'hammerspoon'
cask 'handbrake'
cask 'heaven'
cask 'iina'
cask 'inkscape'
cask 'insomnia'
cask 'iterm2'
cask 'itsycal'
cask 'java'
cask 'jdownloader'
cask 'jumpcut'
cask 'keepassxc'
cask 'keybase'
cask 'mactex'
cask 'mammon'
cask 'menumeters'
cask 'mkvtoolnix'
cask 'mkvtools'
cask 'monitorcontrol'
cask 'mpv'
cask 'multipatch'
cask 'netnewswire'
cask 'openemu'
cask 'opera'
cask 'pacifist'
cask 'paintbrush'
cask 'pencil'
cask 'sequel-pro'
cask 'skim'
cask 'sloth'
cask 'steam'
cask 'sublime-text'
cask 'syncthing'
cask 'transmission'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'xld'


mas 'Bandwidth+', id: 490461369
mas 'Blackmagic Disk Speed Test', id: 425264550
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'LittleIpsum', id: 405772121
mas 'Media-Info', id: 550128418
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Sip', id: 507257563
mas 'The Unarchiver', id: 425424353
mas 'Xcode', id: 497799835
